---
- name: Mkdir play client path dir
  file:
    path: "{{ play_path }}"
    state: directory
    owner: ubuntu
  become: true
  tags: provisioning

- name: Install dependencies
  apt: name={{item}} state=installed
  with_items:
    - unzip
    - libpng-dev
    - redis-server
  become: true

- name: add github ssh key
  copy: >
    src=~/.ssh/id_rsa.github
    dest=/root/.ssh/id_rsa.github
    owner=root
    group=root
    mode=0600
  become: yes

- name: add github ssh key
  copy: >
    src=~/.ssh/id_rsa.github.pub
    dest=/root/.ssh/id_rsa.github.pub
    owner=root
    group=root
    mode=0600
  become: yes

- name: configure ssh to use ansible key for github.com
  template: >
    src=templates/ssh_config.j2
    dest=/root/.ssh/config
    owner=root
    group=root
    mode=0644
  become: yes

- name: Add and load private key to ssh-agent
  shell: "eval `ssh-agent -s` && ssh-add /root/.ssh/id_rsa.github"
  become: yes

- name: Set authorized key took from file
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.github.pub') }}"
  become: yes

- name: clone a private repository
  git: >
    repo={{ git_repo }}
    key_file=/root/.ssh/id_rsa.github
    dest={{ play_path }}
    version={{ git_branch }}
    force=yes
    update=yes
  become: yes

- name: Fix permissions
  file:
    path: /srv
    owner: ubuntu
    group: ubuntu
    mode: 0755
    state: directory
    recurse: yes
  become: yes

#
- name: Configure the Yarn APT key
  apt_key: url=https://dl.yarnpkg.com/debian/pubkey.gpg
  become: yes
  tags: provisioning

- name: Add Yarn repository
  apt_repository:
    repo: 'deb https://dl.yarnpkg.com/debian/ stable main'
    state: present
    update_cache: yes
  become: yes
  tags: provisioning

- name: Install Yarn
  apt:
    pkg: yarn
    state: present
  become: yes
  tags: provisioning

- name: Install PM2
  shell: yarn global add pm2
  become: true
  tags: provisioning

- name: Setup PM2 systemd service
  shell: env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu
  become: true
  tags: provisioning
#

- name: Start PM2 systemd service
  systemd:
    daemon_reload: yes
    enabled: yes
    state: started
    name: pm2-ubuntu
  become: yes
  tags: provisioning

- name: Yarn install
  command: yarn install --pure-lockfile
  args:
    chdir: "{{ play_path }}"
  tags: deployment

- name: Yarn build
  command: yarn build
  args:
    chdir: "{{ play_path }}"
  tags: deployment

- name: Copy pm2.json
  copy:
    src: templates/pm2.json.j2
    dest: "{{ play_path }}/pm2.json"
  tags: deployment

# - name: Set NODE_ENV
#   shell: export NODE_ENV=production
#
# - name: Set NODE_HOST
#   shell: export NODE_HOST=0.0.0.0
#
# - name: Set PORT
#   shell: export PORT=8080

- name: Start play via PM2
  command: pm2 start pm2.json
  args:
    chdir: "{{ play_path }}"
  tags: deployment

- name: Copy the site config
  template:
    src: templates/site.conf.j2
    dest: "/etc/nginx/sites-available/{{ domain_name }}.conf"
  become: yes
  tags: deployment

- name: Activate the site
  file:
    src: "/etc/nginx/sites-available/{{ domain_name }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ domain_name }}.conf"
    state: link
  become: yes
  tags: deployment

- name: Reload nginx
  service:
    name: nginx
    state: reloaded
  become: yes
  tags: deployment
