version: "2"
volumes:
  node_modules:

services:
  game:
    build:
      context: .
      dockerfile: Dockerfile.game
    # volumes:
    #   # - .:/relay
    #   # - .lnd/:/relay/.lnd
    #   - node_modules:/relay/node_modules
    mem_limit: 512M
    mem_reservation: 256M
    ports:
      - "8443:8443"
    command: "npm start"
    env_file:
      - /etc/environment

  # relay:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.relay.mainnet
  #   volumes:
  #     # - .:/relay
  #     # - .lnd/:/relay/.lnd
  #     - node_modules:/relay/node_modules

  #   mem_limit: 512M
  #   mem_reservation: 256M
  #   cpus: 0.5
  #   ports:
  #     - "8080:8080"
  #     - "3000:3000"
  #     - "9735:9735"
  #     - "10009:10009"
  #   command: "lnd --accept-keysend --configfile=/relay/.lnd/lnd.conf && npm start"
  #   environment:
  #     - NODE_ENV=production
  #     - PORT=3000
  #     - NODE_DOMAIN=$NODE_DOMAIN
  #     - NODE_IP=$NODE_IP
  #     - NODE_ALIAS=$NODE_ALIAS
  #     - TRIBES_HOST=$TRIBES_HOST
  #     - MEDIA_HOST=$MEDIA_HOST
  #     - MACAROON_LOCATION=$MACAROON_LOCATION
  #   env_file:
  #     - /etc/environment
