---
# Basic provisioning example
- name: Create AWS resources
  hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
    - cluster_configs.yml

  tasks:
  - name: Debug
    debug:
      msg: "{{item.instance_type}}"
    with_items: "{{cluster_configs}}"

  - include_tasks: terminate-node.yml 
    vars:
      config: "{{item}}"
    with_items: "{{cluster_configs}}"
